create table if not exists public.call_sessions (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  caller_id uuid not null references auth.users(id) on delete cascade,
  callee_id uuid not null references auth.users(id) on delete cascade,
  kind text not null check (kind in ('audio','video')),
  status text not null default 'ringing' check (status in ('ringing','accepted','declined','ended','failed')),
  offer_sdp text,
  answer_sdp text,
  started_at timestamptz not null default now(),
  connected_at timestamptz,
  ended_at timestamptz,
  ended_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.call_ice_candidates (
  id bigint generated by default as identity primary key,
  call_id uuid not null references public.call_sessions(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  candidate text not null,
  sdp_mid text,
  sdp_mline_index integer,
  created_at timestamptz not null default now()
);

create index if not exists call_sessions_callee_status_idx on public.call_sessions(callee_id,status,created_at desc);
create index if not exists call_sessions_caller_idx on public.call_sessions(caller_id,created_at desc);
create index if not exists call_ice_candidates_call_idx on public.call_ice_candidates(call_id,id);

alter table public.call_sessions enable row level security;
alter table public.call_ice_candidates enable row level security;

drop policy if exists call_sessions_participants_select on public.call_sessions;
create policy call_sessions_participants_select on public.call_sessions for select to authenticated
using (auth.uid() = caller_id or auth.uid() = callee_id);

drop policy if exists call_sessions_caller_insert on public.call_sessions;
create policy call_sessions_caller_insert on public.call_sessions for insert to authenticated
with check (
  auth.uid() = caller_id
  and caller_id <> callee_id
  and exists (select 1 from public.conversation_members cm where cm.conversation_id = call_sessions.conversation_id and cm.user_id = auth.uid())
  and exists (select 1 from public.conversation_members cm where cm.conversation_id = call_sessions.conversation_id and cm.user_id = call_sessions.callee_id)
);

drop policy if exists call_sessions_participants_update on public.call_sessions;
create policy call_sessions_participants_update on public.call_sessions for update to authenticated
using (auth.uid() = caller_id or auth.uid() = callee_id)
with check (auth.uid() = caller_id or auth.uid() = callee_id);

drop policy if exists call_ice_participants_select on public.call_ice_candidates;
create policy call_ice_participants_select on public.call_ice_candidates for select to authenticated
using (exists (select 1 from public.call_sessions cs where cs.id = call_ice_candidates.call_id and (cs.caller_id = auth.uid() or cs.callee_id = auth.uid())));

drop policy if exists call_ice_participants_insert on public.call_ice_candidates;
create policy call_ice_participants_insert on public.call_ice_candidates for insert to authenticated
with check (
  sender_id = auth.uid()
  and exists (select 1 from public.call_sessions cs where cs.id = call_ice_candidates.call_id and (cs.caller_id = auth.uid() or cs.callee_id = auth.uid()))
);

alter publication supabase_realtime add table public.call_sessions;
alter publication supabase_realtime add table public.call_ice_candidates;
